services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typeahead
    ports:
      - "3307:3306"

  backend:
    build: ./typeahead-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure

  frontend:
    build: ./typeahead-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
