spring:
  application:
    name: typeahead-backend

  datasource:
    url: jdbc:mysql://mysql:3306/typeahead
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true